# Generated by Django 5.2.5 on 2025-08-18 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expanse', 'Expanse')], max_length=10)),
                ('wallet', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('rupee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.TimeField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
